export const medicalSpecialties = {
  ACUPUNCTURE: 'Acupuntura',
  ALLERGY_AND_IMMUNOLOGY: 'Alergia e imunologia',
  ANESTHESIOLOGY: 'Anestesiologia',
  ANGIOLOGY: 'Angiologia',
  CARDIOLOGY: 'Cardiologia',
  CARDIOVASCULAR_SURGERY: 'Cirurgia cardiovascular',
  HAND_SURGERY: 'Cirurgia da mão',
  HEAD_AND_NECK_SURGERY: 'Cirurgia de cabeça e pescoço',
  DIGESTIVE_SYSTEM_SURGERY: 'Cirurgia do aparelho digestivo',
  GENERAL_SURGERY: 'Cirurgia geral',
  ONCOLOGICAL_SURGERY: 'Cirurgia oncológica',
  PEDIATRIC_SURGERY: 'Cirurgia pediátrica',
  PLASTIC_SURGERY: 'Cirurgia plástica',
  THORACIC_SURGERY: 'Cirurgia torácica',
  VASCULAR_SURGERY: 'Cirurgia vascular',
  INTERNAL_MEDICINE: 'Clínica médica',
  COLOPROCTOLOGY: 'Coloproctologia',
  DERMATOLOGY: 'Dermatologia',
  ENDOCRINOLOGY_AND_METABOLOGY: 'Endocrinologia e metabologia',
  ENDOSCOPY: 'Endoscopia',
  GASTROENTEROLOGY: 'Gastroenterologia',
  MEDICAL_GENETICS: 'Genética médica',
  GERIATRICS: 'Geriatria',
  GYNECOLOGY_AND_OBSTETRICS: 'Ginecologia e obstetrícia',
  HEMATOLOGY_AND_HEMOTHERAPY: 'Hematologia e hemoterapia',
  HOMEOPATHY: 'Homeopatia',
  INFECTOLOGY: 'Infectologia',
  MASTOLOGY: 'Mastologia',
  EMERGENCY_MEDICINE: 'Medicina de emergência',
  FAMILY_AND_COMMUNITY_MEDICINE: 'Medicina de família e comunidade',
  OCCUPATIONAL_MEDICINE: 'Medicina do trabalho',
  TRAFFIC_MEDICINE: 'Medicina do tráfego',
  SPORTS_MEDICINE: 'Medicina esportiva',
  PHYSICAL_MEDICINE_AND_REHABILITATION: 'Medicina física e reabilitação',
  INTENSIVE_CARE_MEDICINE: 'Medicina intensiva',
  LEGAL_MEDICINE_AND_FORENSIC: 'Medicina legal e perícia médica',
  NUCLEAR_MEDICINE: 'Medicina nuclear',
  PREVENTIVE_AND_SOCIAL_MEDICINE: 'Medicina preventiva e social',
  NEPHROLOGY: 'Nefrologia',
  NEUROSURGERY: 'Neurocirurgia',
  NEUROLOGY: 'Neurologia',
  NUTRITIONAL_MEDICINE: 'Nutrologia',
  OPHTHALMOLOGY: 'Oftalmologia',
  CLINICAL_ONCOLOGY: 'Oncologia clínica',
  ORTHOPEDICS_AND_TRAUMATOLOGY: 'Ortopedia e traumatologia',
  OTORHINOLARYNGOLOGY: 'Otorrinolaringologia',
  PATHOLOGY: 'Patologia',
  CLINICAL_PATHOLOGY_AND_LABORATORY_MEDICINE: 'Patologia clínica/medicina laboratorial',
  PEDIATRICS: 'Pediatria',
  PULMONOLOGY: 'Pneumologia',
  PSYCHIATRY: 'Psiquiatria',
  RADIOLOGY_AND_DIAGNOSTIC_IMAGING: 'Radiologia e diagnóstico por imagem',
  RADIOTHERAPY: 'Radioterapia',
  RHEUMATOLOGY: 'Reumatologia',
  UROLOGY: 'Urologia',
  AEROSPACE_MEDICINE: 'Medicina Aeroespacial',
} as const
