default_platform(:ios)

platform :ios do
  desc "Build the iOS application."
  lane :build do |options|
    # Run match to sync certificates and profiles
    match(type: "appstore", readonly: true)

    version_name = options[:version_name]
    build_number = options[:build_number]

    # Set the version and build number
    increment_version_number(version_number: version_name, xcodeproj: "App.xcodeproj")
    increment_build_number(build_number: build_number, xcodeproj: "App.xcodeproj")

    # Sync capacitor
    sh("../node_modules/.bin/npx capacitor sync ios")
    
    # build the app
    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store"
    )
  end

  desc "Deploy the iOS application to TestFlight"
  lane :deploy do
    # You can use pilot to upload to TestFlight
    pilot(
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end

platform :android do
  desc "Build the Android application."
  lane :build do |options|
    version_name = options[:version_name]
    version_code = options[:version_code]

    # Set the version and build number
    increment_version_name(version_name: version_name, gradle_file_path: "../android/app/build.gradle")
    increment_version_code(version_code: version_code, gradle_file_path: "../android/app/build.gradle")

    # Sync capacitor
    sh("../node_modules/.bin/npx capacitor sync android")
    
    # build the app
    gradle(
      task: "assemble",
      build_type: "Release"
    )
  end

  desc "Deploy the Android application to the Play Store"
  lane :deploy do
    # You can use supply to upload to the Play Store
    supply(
      track: 'internal'
    )
  end
end

