networks:
  strivium_api:
    external: false

volumes:
  db_data:
  redis_data:

services:
  api:
    container_name: strivium-api
    build:
      context: .
      dockerfile: Dockerfile.local
    working_dir: /app
    restart: always
    ports:
      - "55000:8000"
    networks:
      - strivium_api
    volumes:
      - "./:/app"
    depends_on:
      - db
      - redis

  db:
    container_name: strivium-db
    image: postgres:16-alpine
    restart: always
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "55001:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    networks:
      - strivium_api

  redis:
    container_name: strivium-redis
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "55002:6379"
    volumes:
      - "redis_data:/data"
    networks:
      - strivium_api

