name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: out

  build-android:
    name: Build Android
    needs: build-web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Setup Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Set Version Properties
        run: echo "VERSION_NAME=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Download Web Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: out

      - name: Build Android App
        working-directory: ./android
        env:
          VERSION_NAME: ${{ env.VERSION_NAME }}
          VERSION_CODE: ${{ github.run_number }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: bundle exec fastlane build version_name:"$VERSION_NAME" version_code:"$VERSION_CODE"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          
  build-ios:
    name: Build iOS
    needs: build-web
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Set Version Properties
        run: echo "VERSION_NAME=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Download Web Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: out

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Build iOS App
        working-directory: ./ios/App
        env:
          VERSION_NAME: ${{ env.VERSION_NAME }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: bundle exec fastlane build version_name:"$VERSION_NAME" build_number:"$BUILD_NUMBER"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: output/App.ipa

  deploy-web:
    name: Deploy Web
    needs: build-web
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: out

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          parent: false
          source: 'out'
          destination: '${{ secrets.GCS_BUCKET }}'

  deploy-android:
    name: Deploy Android
    needs: build-android
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-build

      - name: Deploy to Google Play
        working-directory: ./android
        run: bundle exec fastlane deploy

  deploy-ios:
    name: Deploy iOS
    needs: build-ios
    runs-on: macos-latest
    environment: production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-build

      - name: Deploy to App Store
        working-directory: ./ios/App
        run: bundle exec fastlane deploy

  deploy-web-magalu:
    name: Deploy Web to Magalu Cloud
    needs: build-web
    runs-on: ubuntu-latest
    environment: production-magalu
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: out

      - name: SCP files to Magalu Cloud VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MAGALU_HOST }}
          username: ${{ secrets.MAGALU_USERNAME }}
          key: ${{ secrets.MAGALU_SSH_KEY }}
          source: "out/*"
          target: "/var/www/html"
          strip_components: 1
